"""add indexes to employees

Revision ID: 533df0f1f59a
Revises: 940b68f564f5
Create Date: 2026-05-29 01:55:28.683186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '533df0f1f59a'
down_revision: Union[str, Sequence[str], None] = '940b68f564f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_employees_country', 'employees', ['country'], unique=False)
    op.create_index('idx_employees_job_title', 'employees', ['job_title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_employees_job_title', table_name='employees')
    op.drop_index('idx_employees_country', table_name='employees')
    # ### end Alembic commands ###
